<?php

namespace ContainerHfxEqa3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCe52aQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RCe52aQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RCe52aQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trackRepository' => ['privates', 'App\\Repository\\TrackRepository', 'getTrackRepositoryService', true],
        ], [
            'trackRepository' => 'App\\Repository\\TrackRepository',
        ]);
    }
}
