<?php

namespace ContainerHfxEqa3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NvYdLiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nv_YdLi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nv_YdLi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnswerController::checkAnswer' => ['privates', '.service_locator.RCe52aQ', 'get_ServiceLocator_RCe52aQService', true],
            'App\\Controller\\GameController::createGame' => ['privates', '.service_locator.YnOYFh.', 'get_ServiceLocator_YnOYFh_Service', true],
            'App\\Controller\\GameController::playGame' => ['privates', '.service_locator.JAhWt1A', 'get_ServiceLocator_JAhWt1AService', true],
            'App\\Controller\\GameController::playGameAction' => ['privates', '.service_locator.vERCHOz', 'get_ServiceLocator_VERCHOzService', true],
            'App\\Controller\\ParticipationController::setReadyPlayerStateAction' => ['privates', '.service_locator.BqiPl9f', 'get_ServiceLocator_BqiPl9fService', true],
            'App\\Controller\\TrackController::showTrackAction' => ['privates', '.service_locator.1N2TlV4', 'get_ServiceLocator_1N2TlV4Service', true],
            'App\\Controller\\UserController::loginAction' => ['privates', '.service_locator.0qLwByf', 'get_ServiceLocator_0qLwByfService', true],
            'App\\Controller\\UserController::showUserAction' => ['privates', '.service_locator.YQdkk6O', 'get_ServiceLocator_YQdkk6OService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AnswerController:checkAnswer' => ['privates', '.service_locator.RCe52aQ', 'get_ServiceLocator_RCe52aQService', true],
            'App\\Controller\\GameController:createGame' => ['privates', '.service_locator.YnOYFh.', 'get_ServiceLocator_YnOYFh_Service', true],
            'App\\Controller\\GameController:playGame' => ['privates', '.service_locator.JAhWt1A', 'get_ServiceLocator_JAhWt1AService', true],
            'App\\Controller\\GameController:playGameAction' => ['privates', '.service_locator.vERCHOz', 'get_ServiceLocator_VERCHOzService', true],
            'App\\Controller\\ParticipationController:setReadyPlayerStateAction' => ['privates', '.service_locator.BqiPl9f', 'get_ServiceLocator_BqiPl9fService', true],
            'App\\Controller\\TrackController:showTrackAction' => ['privates', '.service_locator.1N2TlV4', 'get_ServiceLocator_1N2TlV4Service', true],
            'App\\Controller\\UserController:loginAction' => ['privates', '.service_locator.0qLwByf', 'get_ServiceLocator_0qLwByfService', true],
            'App\\Controller\\UserController:showUserAction' => ['privates', '.service_locator.YQdkk6O', 'get_ServiceLocator_YQdkk6OService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AnswerController::checkAnswer' => '?',
            'App\\Controller\\GameController::createGame' => '?',
            'App\\Controller\\GameController::playGame' => '?',
            'App\\Controller\\GameController::playGameAction' => '?',
            'App\\Controller\\ParticipationController::setReadyPlayerStateAction' => '?',
            'App\\Controller\\TrackController::showTrackAction' => '?',
            'App\\Controller\\UserController::loginAction' => '?',
            'App\\Controller\\UserController::showUserAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AnswerController:checkAnswer' => '?',
            'App\\Controller\\GameController:createGame' => '?',
            'App\\Controller\\GameController:playGame' => '?',
            'App\\Controller\\GameController:playGameAction' => '?',
            'App\\Controller\\ParticipationController:setReadyPlayerStateAction' => '?',
            'App\\Controller\\TrackController:showTrackAction' => '?',
            'App\\Controller\\UserController:loginAction' => '?',
            'App\\Controller\\UserController:showUserAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
