<?php

namespace ContainerHfxEqa3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YnOYFh_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YnOYFh.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YnOYFh.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'playlistRepository' => ['privates', 'App\\Repository\\PlaylistRepository', 'getPlaylistRepositoryService', true],
            'stateRepository' => ['privates', 'App\\Repository\\StateRepository', 'getStateRepositoryService', true],
        ], [
            'playlistRepository' => 'App\\Repository\\PlaylistRepository',
            'stateRepository' => 'App\\Repository\\StateRepository',
        ]);
    }
}
