<?php

namespace ContainerHfxEqa3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JAhWt1AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JAhWt1A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JAhWt1A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationRepository', 'getParticipationRepositoryService', true],
            'stateRepository' => ['privates', 'App\\Repository\\StateRepository', 'getStateRepositoryService', true],
        ], [
            'participationRepository' => 'App\\Repository\\ParticipationRepository',
            'stateRepository' => 'App\\Repository\\StateRepository',
        ]);
    }
}
