<?php

namespace ContainerHfxEqa3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1N2TlV4.App\Entity\Track' shared service.
     *
     * @return \App\Entity\Track
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1N2TlV4": it references class "App\\Entity\\Track" but no such service exists.');
    }
}
