<?php

namespace ContainerSqZp0tH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YQdkk6OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YQdkk6O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YQdkk6O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'user' => ['privates', '.errored..service_locator.YQdkk6O.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.YQdkk6O": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'serializer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
