<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqZp0tH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqZp0tH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqZp0tH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqZp0tH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSqZp0tH\App_KernelDevDebugContainer([
    'container.build_hash' => 'SqZp0tH',
    'container.build_id' => '00921f8c',
    'container.build_time' => 1620140656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqZp0tH');
