<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'answer_check' => [[], ['_controller' => 'App\\Controller\\AnswerController::checkAnswer'], [], [['text', '/answers']], [], []],
    'session_create' => [['id'], ['_controller' => 'App\\Controller\\SessionController::createSessionAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/sessions']], [], []],
    'session_destroy' => [[], ['_controller' => 'App\\Controller\\SessionController::destroySessionAction'], [], [['text', '/sessions']], [], []],
    'track_show' => [['id'], ['_controller' => 'App\\Controller\\TrackController::showTrackAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tracks']], [], []],
    'user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::showUserAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\UserController::createUserAction'], [], [['text', '/users']], [], []],
];
